### ISSUE TITLE
Make the follow button work

### ISSUE THREAD

**Issue by GBKS** [GBKS/nosta-me#25]
It does not work (just never implemented it). Key thing is to ensure the users follow list is up-to-date. Might need to add some checks. For example, if no follow list was found, ask if the user really doesn't have one.

**Comment by rolznz** [comment]
@GBKS I can't even see a follow button on user profile pages. Is there one?

**Comment by GBKS** [comment]
I hid it for now (because it doesn't work).

**Comment by GBKS** [comment]
PR #85 re-enables the follow button and adds the required functionality. It's sensitive functionality and there's quite a bit of logic behind the scenes, so I'll need to test it for a few days (different accounts, browsers, devices...) to ensure it's solid.
